
#    - name: eds-rtp-callid2-l
#      udp:
#        port: 2002
#        cluster:
#          name: ingress-rtp-callid2-c
#          service_discovery: eds
#          hash_key: callid
#          endpoints:
#            - name: endpoint-name
#              host:
#                selector:
#                  app: worker
#              port: 1235
#              health_check_port: 1233
---
apiVersion: servicemesh.l7mp.io/v1
kind: VirtualService
metadata:
  name: virtualservice-sample-2
spec:
  selector:
    app: worker
  listeners:
    - name: worker-rtp-callid1-l
      udp:
        port: 1235
        cluster:
          name: worker-rtp-callid1-c
          service_discovery: strictdns
          hash_key: callid
          endpoints:
            - name: endpoint-name
              host:
                address: 127.0.0.1
              port: 8000
---
apiVersion: servicemesh.l7mp.io/v1
kind: VirtualService
metadata:
  name: virtualservice-sample-2
spec:
  selector:
    app: envoy-ingress
  listeners:
    - name: ingrress-rtp-callid1-l
      udp:
        port: 2001
        cluster:
          name: worker-rtp-callid1-c
          service_discovery: strictdns
          hash_key: callid
          endpoints:
            - name: endpoint-name
              host:
                selector:
                  app: worker # 172 ....
              port: 1235
#---
#apiVersion: servicemesh.l7mp.io/v1
#kind: VirtualService
#metadata:
#  name: virtualservice-sample-2
#spec:
#  selector:
#    app: envoy-ingress
#  listeners:
#    - name: ingress-rtp-callid1-l
#      udp:
#        port: 2001
#        cluster:
#          name: ingress-rtp-callid1-c
#          service_discovery: strictdns
#          health_check:
#            interval: 500
#            protocol: TCP
#          hash_key: callid
#          endpoints:
#            - name: endpoint-name
#              host:
#                selector:
#                  app: worker
#              port: 2001
#              health_check_port: 1233
#    - name: ingress-rtp-callid2-l
#      udp:
#        port: 2002
#        cluster:
#          name: ingress-rtp-callid2-c
#          service_discovery: strictdns
#          health_check:
#            interval: 100
#            protocol: TCP
#          hash_key: callid
#          endpoints:
#            - name: endpoint-name
#              host:
#                selector:
#                  app: worker
#              port: 1234
#              health_check_port: 1233
#            #- name: endpoint-name
#            #  host: 127.0.0.1
#            #  port: 1234
