apiVersion: v1
kind: Service
metadata:
  name: operator-service
  namespace: operator-system
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 18000